
CREATE DATABASE RealEstateRD;

USE RealEstateRD;



SELECT DB_NAME() AS Basededatos


CREATE TABLE fact_licencias_construccion(
	ID INT PRIMARY KEY,
	CODIGO_MES INT,
	MES VARCHAR(15),
	ANIO INT,
	CODIGO_CLASIFICACION_SUELO INT,
	CLASIFICACION_SUELO NVARCHAR(50),
	CODIGO_TIPO_SISTEMA_ESTRUCTURAL INT,
	TIPO_SISTEMA_ESTRUCTURAL NVARCHAR(100),
	CODIGO_PROVINCIA INT, 
	PROVINCIA NVARCHAR(100),
	CODIGO_TIPOLOGIA INT,
	TIPOLOGIA NVARCHAR(150),
	CANTIDAD_EDIFICACIONES INT,
	UNIDADES_HABITACIONALES INT,
	LOCALES_COMERCIALES_OFICINAS INT,
	CANTIDAD_USO_DORMITORIOS INT,
	MTS2_TASACION DECIMAL(18,2),
	VALOR_TASADO DECIMAL(18,2),
	PERIMETRO_CONSTRUCCION DECIMAL(18,2),
	EXTENSION_SOLAR_MTS2 DECIMAL(18,2),
	INDICE_CONSTRUCCION_PCT DECIMAL(10,6),
	VALOR_TASADO_M2 DECIMAL(18,6)
);


SELECT * FROM fact_licencias_construccion
